# Generated by Django 3.1.7 on 2021-03-22 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='lastname',
            field=models.CharField(default=1, max_length=80, verbose_name='Apellidos'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('resume', models.TextField(blank=True, verbose_name='Resumen')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.author')),
            ],
        ),
    ]
